### PR TITLE
Remove geoip

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-deluge/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Comment by Roxedus** [comment]
Log indicate it still tries to look for the geoip files, doesnt seem to be a way for it to not attempt to look for the data base.

**Review by Roxedus — APPROVED** [review]

**Comment by prashker** [comment]
Was https://pypi.org/project/python-geoip-python3/ not a contender for replacement?

**Comment by thespad** [comment]
It's a matter of what deluge supports, right now it needs the geoip module, which hasn't been updated since 2014 and will not build against python 3.11

**Comment by prashker** [comment]
Seems like it can fallback to "pygeoip" 
https://git.deluge-torrent.org/deluge/commit/?id=65e5010e7fbdef6cf484368cf8375e9f142a4e69

https://pypi.org/project/pygeoip/ apparently works on 3.4 so I suspect 3.11 is 👍

**Pull request merged**
